import os
import time
import random
import datetime
from core.event_bus import EventBus, EventTypes
from core.timeline import TimelineEngine
from core.temporal_memory import TemporalMemory
from core.prediction_engine import PredictionEngine
from monitors.window_monitor import WindowMonitor
from monitors.keyboard_monitor import KeyboardMonitor
from monitors.idle_monitor import IdleMonitor
from narrative.template_engine import TemplateEngine


def get_ordinal(n):
    if 11 <= (n % 100) <= 13: return str(n) + 'th'
    return str(n) + {1: 'st', 2: 'nd', 3: 'rd'}.get(n % 10, 'th')


def create_transmission_subscriber(template_engine, timeline_engine, memory):
    last_stability = 85

    def subscriber(event_type, payload):
        nonlocal last_stability

        # Ignore standalone stability events as usual
        if event_type in [EventTypes.TIMELINE_STABILITY_CHANGED, EventTypes.TIMELINE_STATE_CHANGED]:
            return

        # 1. Visual Presentation Headers based on event type
        header = "████████ TEMPORAL TRANSMISSION ████████"
        is_prediction_event = False

        if event_type == EventTypes.PREDICTION_REGISTERED:
            header = "████████ TEMPORAL FORECAST ████████"
            is_prediction_event = True
        elif event_type == EventTypes.PREDICTION_VERIFIED:
            header = "████████ PREDICTION VERIFIED ████████"
            is_prediction_event = True
        elif event_type == EventTypes.PREDICTION_AVERTED:
            header = "████████ TIMELINE DEVIATION ████████"
            is_prediction_event = True

        is_transition = (event_type == EventTypes.WINDOW_CHANGED)
        specific_template_key = event_type

        # 2. Contextual Template Key Resolution
        if event_type == EventTypes.WINDOW_CHANGED:
            app_visits = memory.get_app_visits(memory.current_app)
            dominant_sector = memory.get_most_visited_sector()

            if app_visits >= 3:
                if memory.current_sector == dominant_sector and memory.current_sector not in ["Coding", "System"]:
                    specific_template_key = "WindowChanged_Dominant_Deviation"
                else:
                    specific_template_key = "WindowChanged_Repeated"
            else:
                p_sec = memory.prev_sector.lower()
                c_sec = memory.current_sector.lower()
                specific_template_key = f"WindowChanged_{p_sec}_to_{c_sec}"

        elif event_type == EventTypes.IDLE_ENDED:
            if memory.idle_count >= 3:
                specific_template_key = "IdleEnded_Repeated"

        # 3. Stability Metrics
        new_stability = timeline_engine.score
        delta = new_stability - last_stability

        if new_stability >= 90:
            severity = "INFO"
        elif new_stability >= 70:
            severity = "LOW"
        elif new_stability >= 50:
            severity = "MEDIUM"
        elif new_stability >= 25:
            severity = "HIGH"
        else:
            severity = "CRITICAL"

        # 4. Temporal Presentation Dates
        now = datetime.datetime.now()
        future_date = now.replace(year=now.year + 21)

        # 5. Build Rich Payload
        rich_payload = dict(payload)
        rich_payload.update({
            "tx_id": f"TR-83B-{random.randint(10000, 99999)}",
            "future_date": future_date.strftime("%d %B %Y"),
            "transmission_age": 21,
            "subject": "Vedang",
            "old_stability": last_stability,
            "new_stability": new_stability,
            "delta": delta,
            "severity": severity,
            "is_transition": is_transition,

            # Memory Injections
            "prev_app": memory.prev_app,
            "prev_sector": memory.prev_sector,
            "current_app": memory.current_app,
            "current_sector": memory.current_sector,
            "visit_count": memory.get_app_visits(memory.current_app),
            "visit_count_ordinal": get_ordinal(memory.get_app_visits(memory.current_app)),
            "dominant_sector": memory.get_most_visited_sector()
        })

        # 6. Generate Transmission Text
        transmission = template_engine.generate_transmission(specific_template_key, rich_payload)
        if not transmission:
            transmission = template_engine.generate_transmission(event_type, rich_payload)

        # 7. Print with Dynamic Header Frame
        if transmission:
            # We replace the default transmission header generated by the template engine
            # with our specialized prediction headers if necessary.
            lines = transmission.split("\n")
            lines[0] = header
            final_output = "\n".join(lines)

            print(f"\n{final_output}\n")

        # 8. Finalize State
        if not is_prediction_event:
            last_stability = new_stability

    return subscriber


def main():
    print("Initializing Temporal Core Architecture...")

    current_dir = os.path.dirname(os.path.abspath(__file__))
    templates_dir = os.path.join(current_dir, '..', 'data', 'templates')

    bus = EventBus()

    timeline_engine = TimelineEngine(bus)
    memory = TemporalMemory(bus)
    prediction_engine = PredictionEngine(bus, memory)  # <-- NEW
    template_engine = TemplateEngine(templates_dir)

    narrative_subscriber = create_transmission_subscriber(template_engine, timeline_engine, memory)

    # Subscribe to ALL primary and prediction events
    for event_type in dir(EventTypes):
        if not event_type.startswith("__"):
            bus.subscribe(getattr(EventTypes, event_type), narrative_subscriber)

    window_monitor = WindowMonitor(bus)
    keyboard_monitor = KeyboardMonitor(bus)
    idle_monitor = IdleMonitor(bus, idle_threshold_seconds=5.0)

    keyboard_monitor.start()

    print("\nIntegration Test Active. Temporal Oracle Engaged.")
    print("To test Predictions: Go to VS Code and spam Backspace.")
    print("Wait to see Forecast. Then switch to Chrome to Verify it (or wait 90s to Avert it).")
    print("Press Ctrl+C to terminate.\n")

    try:
        while True:
            window_monitor.poll()
            keyboard_monitor.poll()
            idle_monitor.poll()
            timeline_engine.poll()
            prediction_engine.poll()  # <-- NEW: Polls for expired predictions
            time.sleep(0.5)

    except KeyboardInterrupt:
        pass
    finally:
        keyboard_monitor.stop()


if __name__ == "__main__":
    main()